
POST http://localhost:4000/api/credits
Cookie: next-auth.session-token=ckcujejon00167aguiyq75dqg
content-type: application/json

{
    "teamId" : "b5f7e4b6-6329-4131-a082-868ce47248a6",
    "name":"bobby",
    "phone": "19191661",
    "reason": "bad stuff yo"
}